### PR TITLE
Add Spring zuul ratelimit third party integration

### PR DESCRIPTION
**Pull request by lchayoun**

### CODE REVIEW

**Comment by vladimir-bukhtoyarov** [comment]
Looks nice

**Comment by vladimir-bukhtoyarov** [comment]
@lchayoun I have no expirience with Zuul, but if I remember correctly, then Zuul provides asynchronous filter(do not remember since version). Does ```spring-cloud-zuul-ratelimit``` support async filters?  
Keep in mind, that I especially added direct support for Hazelcast and Ignite, because it was impossible to achieve asynchrony while staying in raw JCache API, thus bucket4j-hazelcast and bucket4j-ignite modules are not needed if you do not use async support.

According to ```bucket4j-infinispan``` -  it is actual independently from asynchrony.

**Comment by lchayoun** [comment]
@vladimir-bukhtoyarov Zuul 1 is synchronous, maybe zuul 2?
https://medium.com/netflix-techblog/zuul-2-the-netflix-journey-to-asynchronous-non-blocking-systems-45947377fb5c

**Comment by vladimir-bukhtoyarov** [comment]
Ah yes, zuul 1.x does not support asynchrony. I hope that mature version of zuul 2.0 will be released eventually,  just keep in mind that Bucket4j already has async API.

**Pull request merged**
