### PR TITLE
change Bandwidth's fields to public for runtime checking

### PR DESCRIPTION
**Pull request by Akvel**
For "change configuration of bucket on the fly" feature we should have the way to check current bundwidth settings and current  application settings to decide call replaceConfiguration

### CODE REVIEW

**Comment by vladimir-bukhtoyarov** [comment]
@Akvel, 

In general, I have no objections to add public getters to bandwidth but this feature does not look like major enough to make a new release. Currently, you are able to inspect fields of Bandwidth class with a helper like this:
```java
// just put the helper to the same package with Bandwidth in order to achieve access to package-private fields

package io.github.bucket4j 

public class BandwidthHelper {
   
    public long getCapacity(Bandwidth bandwith) {
        return bandwith.capacity;
    }

    // other getters ...
   
}
```
Since workaround exists, I want to keep this request on hold until the sufficient amount of new features will be ready to make a new release.

**Comment by Akvel** [comment]
> @Akvel,
> 
> In general, I have no objections to add public getters to bandwidth but this feature does not look like major enough to make a new release. Currently, you are able to inspect fields of Bandwidth class with a helper like this:
> 
> ```java
> // just put the helper to the same package with Bandwidth in order to achieve access to package-private fields
> 
> package io.github.bucket4j 
> 
> public class BandwidthHelper {
>    
>     public static long getCapacity(Bandwidth bandwith) {
>         return bandwith.capacity;
>     }
> 
>     // other getters ...
>    
> }
> ```
> 
> Since workaround exists, I want to keep this request on hold until the sufficient amount of new features will be ready to make a new release.

Sure. I will use your workaround in current version 👍

**Comment by vladimir-bukhtoyarov** [comment]
This request is fully covered by https://github.com/vladimir-bukhtoyarov/bucket4j/commit/5477b88f9edc3b2ed4041c70c8473a77925b5e38

Will be released in the scope of release 4.5

**Comment by vladimir-bukhtoyarov** [comment]
released under version 4.5.0

**Pull request closed without merging**
