### PR TITLE
Redis integration spike

### PR DESCRIPTION
**Pull request by user404d**
Added redis integration using lettuce and spring data redis. Unfortunately, not great performance due to the particular implementation path chosen. Hopefully, though, this is useful as reference or as a baseline for others to compare against.

### CODE REVIEW

**Comment by vladimir-bukhtoyarov** [comment]
I will look. 

According to performance, it is not surprising.  Stored procedures(not PL/SQL of course) there is only one way to go if low latency is needed. If you want to achieve low latency you should deliver computation to a place where data stored, instead of fetching data to place where computation happens, that is why JCache based backends work fast. I tried to support Redis Lua scripting directly in the scope of #36 but have stuck a lot by focusing on my regular job. It looks like I will be able to continue at the end of this year. 

Until #36 completion I do not believe in Redis Backend performance without  Lua scripting.  So most likely I will not merge anything from this request(excepting fixes for tests which look good). If you need an immediate early alfa version of 5.0 branch then I can release it in Maven Central.

**Comment by user404d** [comment]
I agree that using redis eval would help, but I wasn't sure how to marry lua scripts getting called to the generic remote command abstraction you have on 5.0. If you have some ideas on how that could work I would be interested to hear those ideas and I might be able to make some progress towards that end.

**Comment by vladimir-bukhtoyarov** [comment]
I started implementation of lua procedures https://github.com/vladimir-bukhtoyarov/bucket4j/tree/5.0/experimental/bucket4j-lua but current state is just mockup

**Comment by vladimir-bukhtoyarov** [comment]
Fixes for unit tests were merged https://github.com/vladimir-bukhtoyarov/bucket4j/commit/86a54f3f04f7a231afe00089a861f96b6b96c8f9

**Pull request closed without merging**
